### ISSUE TITLE
game:start_dialog(dialog, varible, function(answer)) no longer working

### ISSUE THREAD

**Issue by MetalES** [MetalES/Project-Zelda#41]
function(answer) no longer works after replacing sol.main.load by require, that's strange ...

game:start_dialog("_ocarina."..index..".played", function(answer)
  if answer == 1 then
    self:warp_from_ocarina("out")
  else
    self:stop_ocarina()
  end
end)

answer always return nil

Strangely, in the dialog box script, selected_answer return the right value

**Comment by christopho** [comment]
https://github.com/MetalES/Project-Zelda/blob/master/data/scripts/loader/dialog_box.lua#L314

selected_answers is mispelled, it shoud be selected_answer

**Comment by christopho** [comment]
And ok, mispelled is misspelled, it should be misspelled :)

**Comment by MetalES** [comment]
Right right, I didn't see the extra letter, thanks Chris :)
