### ISSUE TITLE
Get rid of all the partitions for some things.

### ISSUE THREAD

**Issue by MetalES** [MetalES/Project-Zelda#42]
Some music use partitions in order to have a certain music playing depending o some actions (Hyrule Field, Phantom Ganon, King Dodongo, Gohdan), this is not convenient, each time, the music has to be reloaded, this leads to some freezes in-game (The music is being loaded on memory and immediately played)

Hyrule Field itself is more then 20 partitions (not moving, dawn of a new day, night, near enemy, morning / evening, on horse)

There should be a solution, I just let this issue there when I'll be doing this kind of stuff, but this solution might require to modify the core engine, mostly the audio.

**Comment by Diarandor** [comment]
This could be a problem of the engine.
I would ask Christopho if it would be possible for him to make some function similar to "sol.audio.preload_sounds()"  but for musics in future versions of the engine (some new function that could be like "sol.audio.preload_music(music_id)", maybe).

**Comment by MetalES** [comment]
Yes that could be a nice add-on to the engine, but I have in my mind something like the LOOPSTART, LOOPEND, but for partitions.

Example : 

PARTITION1_START  lengh in sample
PARTITION1_END      lengh in sample

And then add an event sol.audio.on_partition_finished(partition)
And modify the default sol.audio.play_music() by so

sol.audio.play_music(music, callback(partition))
and sol.audio.jump_to_partition(number)

I always wanted to see something like this, Chris has a better solution, as we talked in the forum (http://forum.solarus-games.org/index.php/topic,708.0.html)

But I wanna see if this is possible, and the possibilities of a such extention

Because preloading a music will have an impact on memory, bigger impact then preloading sounds, actually, preloading all the sounds from my project takes around 70mb in memory, this could be worse for musics, especially for musics with a lot of partitions.

**Comment by MetalES** [comment]
The timer solution kinda worked so this makes this script fixed, re-working things on the source code is not the best solution out there
